name: dm
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - pip:
    - pyyaml==6.0.2
    - easydict==1.13
    - labkey==3.4.0
    - yachalk==0.1.7
    - rich==14.1.0
    - click==8.1.8
    - python-dotenv==1.0.1
    - blake3==1.0.6
    - openpyxl==3.1.5
